name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on:
  #push:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ${{ inputs.debug }} Print start-up data
        run: |
            if [ "${{ inputs.debug }}" = "true" ]; then
                echo "Trigered by" ${{ github.event_name }}"
                echo "Branch " ${{ github.ref_name }}"
                echo "Commit SHA:" ${{ github.sha }}"
                echo "Runner OS ${{ runner.os }}"
      - name: ${{ inputs.debug }} Print when triggered
        run: |
            if [ "${{ inputs.debug }}" = "true" ] && [ "${{ github.branch }}" = "main" ]; then
            echo "I was triggered from main"
      - name: Greeting
        run: echo "Hello, world"